# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 479)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_3 = QtWidgets.QSplitter(self.widget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_3 = QtWidgets.QLabel(self.splitter_3)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox_autosend = QtWidgets.QCheckBox(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_autosend.setFont(font)
        self.checkBox_autosend.setObjectName("checkBox_autosend")
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_findlist = QtWidgets.QComboBox(self.widget)
        self.comboBox_findlist.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBox_findlist.setFont(font)
        self.comboBox_findlist.setEditable(True)
        self.comboBox_findlist.setMaxVisibleItems(30)
        self.comboBox_findlist.setObjectName("comboBox_findlist")
        self.horizontalLayout_3.addWidget(self.comboBox_findlist)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.listWidget_cmdlist = QtWidgets.QListWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.listWidget_cmdlist.setFont(font)
        self.listWidget_cmdlist.setStyleSheet("selection-color: rgb(0, 255, 255);")
        self.listWidget_cmdlist.setObjectName("listWidget_cmdlist")
        self.verticalLayout_2.addWidget(self.listWidget_cmdlist)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(251, 31))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(131, 16))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_connect = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.pushButton_connect.setMinimumSize(QtCore.QSize(60, 41))
        self.pushButton_connect.setMaximumSize(QtCore.QSize(107, 41))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.horizontalLayout.addWidget(self.pushButton_connect)
        self.lineEdit_sendnum = QtWidgets.QLineEdit(self.horizontalGroupBox)
        self.lineEdit_sendnum.setMinimumSize(QtCore.QSize(10, 10))
        self.lineEdit_sendnum.setMaximumSize(QtCore.QSize(25, 41))
        self.lineEdit_sendnum.setMaxLength(300)
        self.lineEdit_sendnum.setObjectName("lineEdit_sendnum")
        self.horizontalLayout.addWidget(self.lineEdit_sendnum)
        self.pushButton_paste = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.pushButton_paste.setMinimumSize(QtCore.QSize(60, 41))
        self.pushButton_paste.setMaximumSize(QtCore.QSize(106, 41))
        self.pushButton_paste.setObjectName("pushButton_paste")
        self.horizontalLayout.addWidget(self.pushButton_paste)
        self.pushButton_clear = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(60, 41))
        self.pushButton_clear.setMaximumSize(QtCore.QSize(106, 41))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout.addWidget(self.pushButton_clear)
        self.pushButton_collect = QtWidgets.QPushButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_collect.sizePolicy().hasHeightForWidth())
        self.pushButton_collect.setSizePolicy(sizePolicy)
        self.pushButton_collect.setMinimumSize(QtCore.QSize(60, 41))
        self.pushButton_collect.setMaximumSize(QtCore.QSize(106, 41))
        self.pushButton_collect.setObjectName("pushButton_collect")
        self.horizontalLayout.addWidget(self.pushButton_collect)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "命令客户端"))
        self.label_3.setText(_translate("MainWindow", "命令列表"))
        self.checkBox_autosend.setText(_translate("MainWindow", "自动发送"))
        self.pushButton.setText(_translate("MainWindow", "清空"))
        self.label_2.setText(_translate("MainWindow", "IP地址"))
        self.label.setText(_translate("MainWindow", "请输入执行命令"))
        self.pushButton_connect.setText(_translate("MainWindow", "发送"))
        self.lineEdit_sendnum.setToolTip(_translate("MainWindow", "执行数量"))
        self.pushButton_paste.setText(_translate("MainWindow", "粘贴"))
        self.pushButton_clear.setText(_translate("MainWindow", "清空"))
        self.pushButton_collect.setText(_translate("MainWindow", "收藏"))

