# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Qtexample\git\pyqt5\AutoMyCCode\db\automyccode.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 536)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.centralWidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_insert_quickly = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_insert_quickly.setMinimumSize(QtCore.QSize(91, 30))
        self.pushButton_insert_quickly.setMaximumSize(QtCore.QSize(91, 41))
        self.pushButton_insert_quickly.setObjectName("pushButton_insert_quickly")
        self.horizontalLayout.addWidget(self.pushButton_insert_quickly)
        self.pushButton_paste = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_paste.setMinimumSize(QtCore.QSize(91, 30))
        self.pushButton_paste.setMaximumSize(QtCore.QSize(91, 41))
        self.pushButton_paste.setObjectName("pushButton_paste")
        self.horizontalLayout.addWidget(self.pushButton_paste)
        self.pushButton_insert = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_insert.setMinimumSize(QtCore.QSize(91, 30))
        self.pushButton_insert.setMaximumSize(QtCore.QSize(91, 41))
        self.pushButton_insert.setObjectName("pushButton_insert")
        self.horizontalLayout.addWidget(self.pushButton_insert)
        self.pushButton_clean = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clean.setMinimumSize(QtCore.QSize(91, 41))
        self.pushButton_clean.setMaximumSize(QtCore.QSize(91, 41))
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.horizontalLayout.addWidget(self.pushButton_clean)
        self.pushButton_regular_mode = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_regular_mode.setMinimumSize(QtCore.QSize(91, 30))
        self.pushButton_regular_mode.setMaximumSize(QtCore.QSize(91, 41))
        self.pushButton_regular_mode.setObjectName("pushButton_regular_mode")
        self.horizontalLayout.addWidget(self.pushButton_regular_mode)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.listWidget_search = QtWidgets.QListWidget(self.splitter)
        self.listWidget_search.setWordWrap(False)
        self.listWidget_search.setObjectName("listWidget_search")
        self.textEdit_inserttext = QtWidgets.QTextEdit(self.splitter)
        self.textEdit_inserttext.setObjectName("textEdit_inserttext")
        self.textEdit_regexpress = QtWidgets.QTextEdit(self.splitter)
        self.textEdit_regexpress.setObjectName("textEdit_regexpress")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_search = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(0, 41))
        self.lineEdit_search.setMaximumSize(QtCore.QSize(16777215, 41))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout_2.addWidget(self.lineEdit_search)
        self.pushButton_showresult = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_showresult.setMinimumSize(QtCore.QSize(91, 41))
        self.pushButton_showresult.setMaximumSize(QtCore.QSize(91, 41))
        self.pushButton_showresult.setObjectName("pushButton_showresult")
        self.horizontalLayout_2.addWidget(self.pushButton_showresult)
        self.pushButton_searchclean = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_searchclean.setMinimumSize(QtCore.QSize(91, 41))
        self.pushButton_searchclean.setMaximumSize(QtCore.QSize(91, 41))
        self.pushButton_searchclean.setObjectName("pushButton_searchclean")
        self.horizontalLayout_2.addWidget(self.pushButton_searchclean)
        self.pushButton_toclipboard = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_toclipboard.setMinimumSize(QtCore.QSize(91, 41))
        self.pushButton_toclipboard.setMaximumSize(QtCore.QSize(91, 41))
        self.pushButton_toclipboard.setObjectName("pushButton_toclipboard")
        self.horizontalLayout_2.addWidget(self.pushButton_toclipboard)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.textEdit_showresult = QtWidgets.QTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_showresult.setFont(font)
        self.textEdit_showresult.setObjectName("textEdit_showresult")
        self.verticalLayout_2.addWidget(self.textEdit_showresult)
        self.gridLayout.addWidget(self.splitter_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 838, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuOperation = QtWidgets.QMenu(self.menuBar)
        self.menuOperation.setObjectName("menuOperation")
        self.menuRegex_Mode = QtWidgets.QMenu(self.menuOperation)
        self.menuRegex_Mode.setObjectName("menuRegex_Mode")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSearchText = QtWidgets.QAction(MainWindow)
        self.actionSearchText.setObjectName("actionSearchText")
        self.actionImage_2_Text = QtWidgets.QAction(MainWindow)
        self.actionImage_2_Text.setObjectName("actionImage_2_Text")
        self.actionC_C = QtWidgets.QAction(MainWindow)
        self.actionC_C.setObjectName("actionC_C")
        self.actionPython = QtWidgets.QAction(MainWindow)
        self.actionPython.setObjectName("actionPython")
        self.actionCalculator = QtWidgets.QAction(MainWindow)
        self.actionCalculator.setObjectName("actionCalculator")
        self.actionSSH = QtWidgets.QAction(MainWindow)
        self.actionSSH.setObjectName("actionSSH")
        self.actioncommentadd = QtWidgets.QAction(MainWindow)
        self.actioncommentadd.setObjectName("actioncommentadd")
        self.menuRegex_Mode.addAction(self.actionC_C)
        self.menuRegex_Mode.addAction(self.actionPython)
        self.menuOperation.addAction(self.actionSearchText)
        self.menuOperation.addAction(self.menuRegex_Mode.menuAction())
        self.menuOperation.addAction(self.actionImage_2_Text)
        self.menuOperation.addAction(self.actionCalculator)
        self.menuOperation.addAction(self.actionSSH)
        self.menu.addAction(self.actioncommentadd)
        self.menuBar.addAction(self.menuOperation.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_insert_quickly.setText(_translate("MainWindow", "自动写入"))
        self.pushButton_paste.setText(_translate("MainWindow", "粘贴"))
        self.pushButton_insert.setText(_translate("MainWindow", "写入"))
        self.pushButton_clean.setText(_translate("MainWindow", "清除"))
        self.pushButton_regular_mode.setText(_translate("MainWindow", "正则完成"))
        self.pushButton_showresult.setText(_translate("MainWindow", "ShowResult"))
        self.pushButton_searchclean.setText(_translate("MainWindow", "Clear"))
        self.pushButton_toclipboard.setText(_translate("MainWindow", "粘上"))
        self.menuOperation.setTitle(_translate("MainWindow", "Operation"))
        self.menuRegex_Mode.setTitle(_translate("MainWindow", "Regex Mode"))
        self.menu.setTitle(_translate("MainWindow", "添加操作"))
        self.actionSearchText.setText(_translate("MainWindow", "SearchText"))
        self.actionImage_2_Text.setText(_translate("MainWindow", "图片转字符"))
        self.actionC_C.setText(_translate("MainWindow", "C/C++"))
        self.actionPython.setText(_translate("MainWindow", "Python"))
        self.actionCalculator.setText(_translate("MainWindow", "Python\n"
"Calculator"))
        self.actionSSH.setText(_translate("MainWindow", "SSH"))
        self.actioncommentadd.setText(_translate("MainWindow", "注释添加"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

