# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Qtexample\git\pyqt5\AutoMyCCode\db\ssh.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(704, 474)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(141, 12))
        self.label_4.setMaximumSize(QtCore.QSize(141, 12))
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_ip.setMinimumSize(QtCore.QSize(141, 20))
        self.lineEdit_ip.setMaximumSize(QtCore.QSize(141, 20))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.verticalLayout.addWidget(self.lineEdit_ip)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(141, 12))
        self.label.setMaximumSize(QtCore.QSize(141, 12))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit_usr = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_usr.setMinimumSize(QtCore.QSize(141, 20))
        self.lineEdit_usr.setMaximumSize(QtCore.QSize(141, 20))
        self.lineEdit_usr.setObjectName("lineEdit_usr")
        self.verticalLayout_2.addWidget(self.lineEdit_usr)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(141, 12))
        self.label_2.setMaximumSize(QtCore.QSize(141, 12))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_pwd.setMinimumSize(QtCore.QSize(141, 20))
        self.lineEdit_pwd.setMaximumSize(QtCore.QSize(141, 20))
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.verticalLayout_3.addWidget(self.lineEdit_pwd)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(141, 12))
        self.label_3.setMaximumSize(QtCore.QSize(141, 12))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.lineEdit_port = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_port.setMinimumSize(QtCore.QSize(141, 20))
        self.lineEdit_port.setMaximumSize(QtCore.QSize(141, 20))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.verticalLayout_4.addWidget(self.lineEdit_port)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textEdit_cmdlist = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_cmdlist.setObjectName("textEdit_cmdlist")
        self.verticalLayout_5.addWidget(self.textEdit_cmdlist)
        self.pushButton_sendcmd = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sendcmd.sizePolicy().hasHeightForWidth())
        self.pushButton_sendcmd.setSizePolicy(sizePolicy)
        self.pushButton_sendcmd.setMinimumSize(QtCore.QSize(251, 41))
        self.pushButton_sendcmd.setObjectName("pushButton_sendcmd")
        self.verticalLayout_5.addWidget(self.pushButton_sendcmd)
        self.textEdit_showresult = QtWidgets.QTextEdit(self.splitter)
        self.textEdit_showresult.setObjectName("textEdit_showresult")
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "IP地址"))
        self.label.setText(_translate("Form", "用户名"))
        self.label_2.setText(_translate("Form", "密码"))
        self.label_3.setText(_translate("Form", "端口"))
        self.pushButton_sendcmd.setText(_translate("Form", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

